version: '3.8'

services:
  backend:
    container_name: nodejs_backend
    image: cleowoman/backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4007"
    command: npm run dev
    networks:
      - backend_network

  frontend:
    container_name: react_frontend
    image: cleowoman/frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3007"
    command: npm run start
    networks:
      - frontend_network

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge
