name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPO: cleowoman
      BACKEND_DIR: backend
      FRONTEND_DIR: frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: |
          # Build the Frontend Docker image
          docker build -t $DOCKER_REPO-frontend $FRONTEND_DIR

          # Build the Backend Docker image
          docker build -t $DOCKER_REPO-backend $BACKEND_DIR

          # Log in to Docker Hub using your credentials
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

          # Push the Docker images to Docker Hub
          docker push $DOCKER_REPO-frontend
          docker push $DOCKER_REPO-backend
