name: Full-Stack Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Build the Frontend
      - name: Build Frontend
        working-directory: /app/frontend # Specify the frontend directory
        run: 
          npm yarn install
          npm run build

      # Build the Backend
      - name: Build Backend
        working-directory: /app/backend # Specify the backend directory
        run: 
          npm install
          # Add any additional backend build steps here

      # Deploy to Azure, Docker, or any other desired platform
      - name: Deploy
        env:
          # Add environment variables for deployment
          FRONTEND_DIR: frontend
          BACKEND_DIR: backend
          # Add other environment variables as needed
        run: 
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t cleowoman/workout .
          docker push cleowoman/workout
          
          # You can use this step to deploy your application to Azure, Docker, etc.
          # Example deployment command:
          # docker-compose up -d
          # Add your deployment commands here

